services: 
  jellyswarrm-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: jellyswarrm-proxy:latest
    container_name: jellyswarrm-proxy
    ports:
      - "8090:3000"
    volumes:
      - ./data:/app/data
    extra_hosts:
      - 'lj1.tyraelqp.top:host-gateway'
    environment:
      - JELLYSWARRM_USERNAME=admin
      - JELLYSWARRM_PASSWORD=qweqweqwe # Change this in production!
      - RUST_LOG=jellyswarrm_proxy=debug 